DROP DATABASE IF EXISTS TEMP;
CREATE DATABASE TEMP;
USE TEMP;
CREATE TABLE DIRECTIONS(
	ID INT PRIMARY KEY,
	NAME TEXT,
	FACULTY TEXT,
	KEYS_PLUS TEXT, 
	BALL_K INT, 
	BALL_B INT, 
	URL TEXT, 
	ACTIVE BOOL, 
	DESCR TEXT, 
	PROFILE_NAME TEXT
	);
CREATE TABLE SPHERES(
	ID INT PRIMARY KEY,
	NAME TEXT
	);
CREATE TABLE SUBJECTS(
	ID INT PRIMARY KEY,
	NAME TEXT
	);
CREATE TABLE DIR_SPHERES(
	ID_DIR INT,
	ID_SPHERE INT,
	FOREIGN KEY(ID_DIR) 
	REFERENCES DIRECTIONS(ID),
	FOREIGN KEY(ID_SPHERE) 
	REFERENCES SPHERES(ID)
	);
CREATE TABLE DIR_SUBJECTS(
	ID_DIR INT,
	ID_SUB INT,
	FOREIGN KEY(ID_DIR) 
	REFERENCES DIRECTIONS(ID),
	FOREIGN KEY(ID_SUB) 
	REFERENCES SUBJECTS(ID)
	);
CREATE TABLE MSGS(
	PAY TEXT NOT NULL,
	MSG TEXT
	);

CREATE TABLE USERS(
	ID INT PRIMARY KEY,
	LK_CODE INT,
	SUBSCRIBE BOOL,
	LAST_NEWS DATETIME,
	UNIQUE(LK_CODE)
	);
CREATE TABLE USERS_SPHERES(
	ID_USER INT,
	ID_SPHERE INT,
	FOREIGN KEY(ID_USER) 
	REFERENCES USERS(ID),
	FOREIGN KEY(ID_SPHERE) 
	REFERENCES SPHERES(ID)
	);
CREATE TABLE USERS_SUBJECTS(
	ID_USER INT,
	ID_SUB INT,
	FOREIGN KEY(ID_USER) 
	REFERENCES USERS(ID),
	FOREIGN KEY(ID_SUB) 
	REFERENCES SUBJECTS(ID)
	);
INSERT INTO SPHERES(ID,NAME) VALUES(1,'IT-технологии');
INSERT INTO SPHERES(ID,NAME) VALUES(2,'Электроника');
INSERT INTO SPHERES(ID,NAME) VALUES(3,'Энергетика');
INSERT INTO SPHERES(ID,NAME) VALUES(4,'Машиностроение');
INSERT INTO SPHERES(ID,NAME) VALUES(5,'Безопасность');
INSERT INTO SPHERES(ID,NAME) VALUES(6,'Авиация');
INSERT INTO SPHERES(ID,NAME) VALUES(7,'Общество');
INSERT INTO SPHERES(ID,NAME) VALUES(8,'Экономика');
INSERT INTO SPHERES(ID,NAME) VALUES(9,'Химия');
INSERT INTO SPHERES(ID,NAME) VALUES(10,'Языки');
INSERT INTO SPHERES(ID,NAME) VALUES(11,'Физика');
INSERT INTO SUBJECTS(ID,NAME) VALUES(1,'math');
INSERT INTO SUBJECTS(ID,NAME) VALUES(2,'informatics');
INSERT INTO SUBJECTS(ID,NAME) VALUES(3,'physics');
INSERT INTO SUBJECTS(ID,NAME) VALUES(4,'chemistry');
INSERT INTO SUBJECTS(ID,NAME) VALUES(5,'biology');
INSERT INTO SUBJECTS(ID,NAME) VALUES(6,'social_science');
INSERT INTO SUBJECTS(ID,NAME) VALUES(7,'history');
INSERT INTO SUBJECTS(ID,NAME) VALUES(8,'foreign_language');
INSERT INTO SUBJECTS(ID,NAME) VALUES(9,'literature');
INSERT INTO SUBJECTS(ID,NAME) VALUES(10,'geography');
	
